"use client";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import Navbar from "../components/Navbar";
// import Main from "../components/Main";

import {
  Navbar,
  Main,
  Carousel,
  ProjectModal,
  Projects,
  Offers,
} from "../components";
import { useEffect } from "react";
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const divRef = useRef(null);
  var scrollHeight = 0;
  const changeNavbarColor = () => {
    // if (window !== undefined) {
    //   var body: any = document.querySelector(".navbar");
    //   var h = window.innerHeight;
    //   console.log("scrolling", window.scrollY);
    //   body.style.transition = ".3s ease-in-out ";
    //   var scrollingPostion: number = window.scrollY - 300;
    //   if (h < scrollingPostion) {
    //     body.style.background = "rgba(22,22,22,.9)";
    //   } else {
    //     body.style.background = "black";
    //   }
    // }
  };
  const div: any = divRef.current;
  useEffect(() => {
    if (window !== undefined) {
      window?.addEventListener("scroll", changeNavbarColor);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Flekenstine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="body" ref={divRef}>
        <Main />
        <Navbar />

        <Projects />
        <Offers />

        {/* <ProjectModal /> */}
      </div>
    </>
  );
}
